---
# Steps primarily learned from:
# http://docs.openstack.org/developer/bifrost/readme.html
# ...up to the end of the "installation" section.

- name: Enable EPEL
  yum:
    name: epel-release
    state: present

- name: Install deps
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - mlocate

- name: Disable selinux
  selinux:
    state: disabled

- name: Generate a an SSH key for root
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Wipe bifrost clone
  file:
    path: /usr/src/bifrost
    state: absent

- name: Clone bifrost
  git:
    repo: https://git.openstack.org/openstack/bifrost.git
    dest: /usr/src/bifrost
    version: master

- name: Template group vars
  template:
    src: "group_vars.{{ item }}.j2"
    dest: "/usr/src/bifrost/playbooks/inventory/group_vars/{{ item }}"
  with_items:
    - baremetal
    - localhost
    - target

- name: Run the env setup script
  shell: >
    bash /usr/src/bifrost/scripts/env-setup.sh
  args:
    creates: /etc/.bifrost-env-setup

- name: Mark env setup complete
  file: 
    path: /etc/.bifrost-env-setup
    state: directory

- name: Source ansible env-setup
  shell: >
    source /opt/stack/ansible/hacking/env-setup
  args:
    creates: /etc/.ansible-env-setup

- name: Mark env setup complete
  file: 
    path: /etc/.ansible-env-setup
    state: directory

- name: Annnnd! We run the installation playbook.
  shell: >
    ansible-playbook -i inventory/target install.yaml
  args:
    chdir: /usr/src/bifrost/playbooks
    creates: /etc/.bifrost-installed

- name: Mark bifrost install complete
  file: 
    path: /etc/.bifrost-installed
    state: directory
