---
- hosts: undercloud
  vars_files:
    - vars/instack.yml
    - vars/undercloud.yml
    - vars/network.yml
    - vars/undercloud_vlans.yml
  tasks: []
  roles:
    # - { role: undercloud }
    # - { role: build_images }
    # - { role: instackenv }
    # - { role: dns }
    # - { role: undercloud-vlans }
    # - { role: heat-templates }
    # - { role: overcloud_deploy }
    # - { role: overcloud_networking }
    - { role: lbaas }