---
# A suite of things to do after bifrost is installed.
# ...such as configuring ironic.

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Make sure the ironic logs directory exists
  file:
    path: /var/log/ironic
    owner: ironic
    group: ironic
    state: directory

# Why not template?
# ...this file is already quite customized, with things we don't yet customize.

- name: Remove pxe_amt from ironic.conf
  lineinfile:
    dest: /etc/ironic/ironic.conf
    regexp: 'pxe_amt'
    state: absent

- name: Add the line with proper enabled_drivers
  lineinfile:
    dest: /etc/ironic/ironic.conf
    regexp: 'agent_ipmitool,agent_ilo,agent_ucs,pxe_ssh,pxe_ipmitool,pxe_ilo'
    insertafter: '^enabled_network_interfaces'
    line: 'enabled_drivers = agent_ipmitool,agent_ilo,agent_ucs,pxe_ssh,pxe_ipmitool,pxe_ilo'
  register: add_enabled_drivers

- name: Restart ironic services when changing ironic.conf
  service:
    name: "{{ item }}"
    state: restarted
  when: add_enabled_drivers.changed
  with_items:
    - ironic-api
    - ironic-conductor
    - ironic-inspector

- name: Ensure ironic services running
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - ironic-api
    - ironic-conductor
    - ironic-inspector

# dhcp-range=192.168.10.50,192.168.10.100,12h
- name: Ensure default DHCP range line is missing from dnsmasq.conf
  lineinfile:
    dest: /etc/dnsmasq.conf
    regexp: 'dhcp-range=192.168.1.200,192.168.1.250,12h'
    state: absent


- name: Add the line with proper DHCP range to dnsmasq
  lineinfile:
    dest: /etc/dnsmasq.conf
    regexp: '{{ pxe_dhcp_start }},{{ pxe_dhcp_end }}'
    line: 'dhcp-range={{ pxe_dhcp_start }},{{ pxe_dhcp_end }},12h'
  register: add_dhcp_range

- name: Restart dnsmasq when adding dhcp range
  service:
    name: dnsmasq
    state: restarted
  when: add_dhcp_range.changed

- name: Ensure dnsmasq is running, always
  service:
    name: dnsmasq
    state: started

  