---

- name: Dun dun dunnnnnnnn DEPLOY THE OVERCLOUD.
  shell: > 
    source /home/stack/stackrc && 
    openstack overcloud deploy --templates
    --compute-scale 3 --control-scale 2
    --ceph-storage-scale 2 -e /usr/share/openstack-tripleo-heat-templates/environments/storage-environment.yaml | tee /home/stack/deploy_overcloud.log
  args: 
    chdir: "/home/stack"
  become: true
  become_user: stack


openstack overcloud deploy --templates --compute-scale 3 --control-scale 2 --ntp-server time.nist.gov --ceph-storage-scale 2 -e /usr/share/openstack-tripleo-heat-templates/environments/storage-environment.yaml | tee /home/stack/deploy_overcloud.log
