---
- hosts: allinone
  vars_files:
    - vars/main.yml
  tasks: []
  roles:
    # - { role: docker-install }
    # - { role: dougbtv.kpm-install , kpm_version: "v0.21.2" }
    # - { role: openshift-install }
    # - { role: openshift-up }
    # - { role: kpm-registry }
    - { role: openshift-aio-dns-hack }